version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.react
    volumes:
      - ./react-docker:/app
    ports:
      - "3000:3000"
    command: npm start
    working_dir: /react-docker

  python-app:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      - ./python-docker:/app
    ports:
      - "5000:5000"
    command: python3 app.py
    working_dir: /python-docker
